General:
  SEED: 123
  INTERSECTION_THRESHOLD: 0.1
  FATNESS: 0.5
  NUM_SCENES: 250
  VIDEO_LEN: 3
  FPS: 30
  DEGREE: 0
  POINT:
  PROJECTION_X: [-1.5, 2.5]
  PROJECTION_Y: [-1.5, 1.5]
  ROT_DISCRETE: False
  OUTPUT_PATH: "output/ds_mixed_medium_slope"
  RENDER_VIDEO: False
  SAVE_LAST_FRAME_IMAGE: True
  SAVE_FIRST_FRAME_IMAGE: True
  # 中高堆叠概率，形成多层结构
  STACK_ON_EXISTING_PROB: 0.6

Scene:
  # 中等高度塔
  num_blocks: 16
  num_colors:
    yellow: 5
    blue: 5
    green: 3
    red: 3

  sizes:
    (0.5, 0.5, 0.5): 4        # 小方块
    (0.5, 0.5, 1.5): 6        # 竖直长条
    (1.5, 0.5, 0.5): 6        # 横着长条

  rot_range: [0, 360]

  # 木 + 金属 + 石头 组合材质
  num_materials:
    wood: 6
    metal: 6
    stone: 4


