General:
  SEED: 42
  INTERSECTION_THRESHOLD: 0.01
  FATNESS: 0.5
  NUM_SCENES: 1
  VIDEO_LEN: 6
  FPS: 30
  ROT_DISCRETE: False
Scene:
  num_blocks: 29
  num_colors: 
    yellow: 13
    blue: 14
    white: 2
  sizes: 
    (0.5, 0.5, 1.5): 16
    (1.5, 0.5, 0.5): 13 
  rot_range: [0, 360]
  material: "wood"